#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTests.Views.Estimates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Estimates/NewEstimate.cshtml")]
    public partial class NewEstimate : System.Web.Mvc.WebViewPage<dynamic>
    {
        public NewEstimate()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Estimates\NewEstimate.cshtml"
  
    ViewBag.Title = "New Estimate";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 115), Tuple.Create("\"", 145)
, Tuple.Create(Tuple.Create("", 122), Tuple.Create<System.Object, System.Int32>(Href("~/Styles/StyleSheet.css")
, 122), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 189), Tuple.Create("\"", 223)
, Tuple.Create(Tuple.Create("", 196), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery-ui.min.css")
, 196), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 267), Tuple.Create("\"", 312)
, Tuple.Create(Tuple.Create("", 274), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery-ui.structures.min.css")
, 274), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 356), Tuple.Create("\"", 396)
, Tuple.Create(Tuple.Create("", 363), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery-ui.theme.min.css")
, 363), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 425), Tuple.Create("\"", 457)
, Tuple.Create(Tuple.Create("", 431), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-ui.min.js")
, 431), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\n\n <script>\r\n  $(function() {\r\n      $(\"#tabs\").tabs();\r\n      $(\"#date" +
"picker\").datepicker();\r\n      $(\"#datepicker\").datepicker(\'setDate\', new Date())" +
";\r\n  });\n</script>\n\n<h2>New Estimate</h2>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"datepicker\"");

WriteLiteral(" class=\"col-sm-2 control-label\"");

WriteLiteral(">Date:</label>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"date\"");

WriteLiteral(" id=\"datepicker\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Date\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"road\"");

WriteLiteral(" class=\"col-sm-2 control-label\"");

WriteLiteral(">Road:</label>\r\n                <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" name=\"road\"");

WriteLiteral(" id=\"road\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Enter the road\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </form>\r\n    </div>\r\n</div" +
">\r\n\r\n<div");

WriteLiteral(" id=\"tabs\"");

WriteLiteral(">\r\n<ul>\r\n<li><a");

WriteLiteral(" href=\"#tabs-1\"");

WriteLiteral(">Material</a></li>\r\n<li><a");

WriteLiteral(" href=\"#tabs-2\"");

WriteLiteral(">Equipment</a></li>\r\n<li><a");

WriteLiteral(" href=\"#tabs-3\"");

WriteLiteral(">Labor</a></li>\r\n</ul>\r\n<div");

WriteLiteral(" id=\"tabs-1\"");

WriteLiteral(">\r\n<p>Material</p>\r\n</div>\r\n<div");

WriteLiteral(" id=\"tabs-2\"");

WriteLiteral(">\r\n<p>Equipment</p>\r\n</div>\r\n<div");

WriteLiteral(" id=\"tabs-3\"");

WriteLiteral(">\r\n<p>Labor</p>\r\n</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
