#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTests.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_GenericGrid.cshtml")]
    public partial class GenericGrid : System.Web.Mvc.WebViewPage<dynamic>
    {
        public GenericGrid()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_GenericGrid.cshtml"
  
    var grid = (WebGrid)ViewBag.Grid;
    var columnSet = ViewBag.ColumnSet;

            
            #line default
            #line hidden
WriteLiteral("\n\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 115), Tuple.Create("\"", 145)
, Tuple.Create(Tuple.Create("", 122), Tuple.Create<System.Object, System.Int32>(Href("~/Styles/StyleSheet.css")
, 122), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\n\n        <script>\n            $(function () {\r\n                $(\'.edit-mode\'" +
").hide();\n                initializeFormEvents();\r\n                initializeGri" +
"dItemEvents();\r\n                initializeSpinny();\r\n            });\n\n          " +
"  function initializeFormEvents() {\r\n                $(\'#add\').on(\'click\', funct" +
"ion () {addItem($(this));});\r\n            }\r\n            \r\n            // New wa" +
"y of doing .live in jQuery 1.9.1\r\n            function initializeGridItemEvents(" +
") {\r\n                $(document).on(\'click\', \'.edit-item\', function () { editBoo" +
"k($(this)); });\r\n                $(document).on(\'click\', \'.save-item\', function " +
"() { saveBook($(this)); });\r\n                $(document).on(\'click\', \'.delete-it" +
"em\', function () { deleteBook($(this)); });\r\n                $(document).on(\'cli" +
"ck\', \'.save-new-item\', function () {\r\n                    $(\'.save-new-item\').re" +
"moveClass(\"save-new-item\").addClass(\"save-item\");\r\n                    saveBook(" +
"$(this));\r\n                });\r\n            }\r\n\r\n            // http://stackover" +
"flow.com/questions/68485/how-to-show-loading-spinner-in-jquery\r\n            func" +
"tion initializeSpinny() {\r\n                var loading = $(\'#loadingDiv\');\r\n    " +
"            loading.hide();\r\n                $(document)\r\n                  .aja" +
"xStart(function () {\r\n                      loading.show();\r\n                  }" +
")\r\n                  .ajaxStop(function () {\r\n                      loading.hide" +
"();\r\n                  });\r\n            }\r\n\n            function setArrows() {\r\n" +
"                var dir = $(\'#dir\').val();\r\n                var col = $(\'#col\')." +
"val();\r\n                var header = $(\'th a[href*=\' + col + \']\');\r\n\r\n          " +
"      if (dir == \'Ascending\') {\r\n                    header.text(header.text() +" +
" \' ▲\');\r\n                }\r\n\r\n                if (dir == \'Descending\') {\r\n      " +
"              header.text(header.text() + \' ▼\');\r\n                }\r\n\r\n         " +
"       $(\'.edit-mode\').hide();\r\n                $(\'.display-mode\').show();\r\n    " +
"        };\r\n\r\n            function addItem(element) {\r\n                // Disabl" +
"e add button.  Add cannot be re-enabled until we get the ID of the new row back " +
"from the server.\r\n                element.attr(\"disabled\", true).addClass(\"disab" +
"led\");\r\n\r\n                // Add a row.\r\n                var newTableRow = $(\'ta" +
"ble\').append(\'<tr>\'+");

            
            #line 66 "..\..\Views\Shared\_GenericGrid.cshtml"
                                                      Write(ViewBag.InlineNewRow);

            
            #line default
            #line hidden
WriteLiteral(@"+'</tr>');

                var newRow = newTableRow.find(""#-1"").parents('tr:first');
                // Hide the display mode fields and show the edit mode fields.
                newRow.find('.edit-mode').show();
                newRow.find('.display-mode').hide();

");

WriteLiteral("                ");

            
            #line 73 "..\..\Views\Shared\_GenericGrid.cshtml"
           Write(ViewBag.PopulateDropDownLists);

            
            #line default
            #line hidden
WriteLiteral(@"
            }

            function editBook(element) {
                var tr = element.parents('tr:first');
                tr.find('.edit-mode, .display-mode').toggle();
            };

            function saveBook(element) {
                var tr = element.parents('tr:first');
                var itemId = element.prop('id');

                // Look at EngineContext.Current.Resolve<GenericController>() to be able to call the controller methods directly.
                // See http://stackoverflow.com/questions/5960664/calling-a-method-in-the-controller
");

WriteLiteral("                ");

            
            #line 87 "..\..\Views\Shared\_GenericGrid.cshtml"
           Write(ViewBag.EditGetters);

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 88 "..\..\Views\Shared\_GenericGrid.cshtml"
           Write(ViewBag.DisplaySetters);

            
            #line default
            #line hidden
WriteLiteral("\n\n                // Post the data so the server saves it.\n                \n     " +
"           $.post(\n                    \'");

            
            #line 93 "..\..\Views\Shared\_GenericGrid.cshtml"
                Write(ViewBag.PostPath);

            
            #line default
            #line hidden
WriteLiteral("\',\n");

WriteLiteral("                    ");

            
            #line 94 "..\..\Views\Shared\_GenericGrid.cshtml"
               Write(ViewBag.PostbackParams);

            
            #line default
            #line hidden
WriteLiteral(@" ,
                    function (item) {
                        var newItemId = item.ItemId;
                        // For a new entry, there's three id's, one for each button, that need to get updated.
                        tr.find('#-1').attr(""id"", newItemId);
                        tr.find('#-1').attr(""id"", newItemId);
                        tr.find('#-1').attr(""id"", newItemId);
                        $('#add').attr(""disabled"", false).removeClass(""disabled"");
                    });
                
                // Revert to display mode.
                tr.find('.edit-mode, .display-mode').toggle();
            };

            function deleteBook(element) {
                var flag = confirm('Are you sure you want to delete this record?');

                if (flag) {
                    var tr = element.parents('tr:first');
                    tr.fadeOut(400, function () { tr.remove(); });
                    var itemId = element.prop('id');
                    $.post('");

            
            #line 115 "..\..\Views\Shared\_GenericGrid.cshtml"
                       Write(ViewBag.DeletePath);

            
            #line default
            #line hidden
WriteLiteral("\', { ItemId: itemId });\r\n                }\r\n            };\r\n        </script>\n   " +
"     <div");

WriteLiteral(" id=\'loadingDiv\'");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 4821), Tuple.Create("\"", 4847)
, Tuple.Create(Tuple.Create("", 4827), Tuple.Create<System.Object, System.Int32>(Href("~/Images/spinner.gif")
, 4827), false)
);

WriteLiteral("/></div> \n        <div");

WriteLiteral(" id=\"grid\"");

WriteLiteral(">\n");

WriteLiteral("            ");

            
            #line 121 "..\..\Views\Shared\_GenericGrid.cshtml"
       Write(grid.GetHtml(
                tableStyle : "table",
                alternatingRowStyle : "alternate",
                selectedRowStyle: "selected",
                headerStyle : "header",
                columns: @columnSet));

            
            #line default
            #line hidden
WriteLiteral("\n        \n");

WriteLiteral("            ");

            
            #line 128 "..\..\Views\Shared\_GenericGrid.cshtml"
       Write(Html.Hidden("dir", grid.SortDirection));

            
            #line default
            #line hidden
WriteLiteral(" \n");

WriteLiteral("            ");

            
            #line 129 "..\..\Views\Shared\_GenericGrid.cshtml"
       Write(Html.Hidden("col", grid.SortColumn));

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n        \n        <button");

WriteLiteral(" id=\"add\"");

WriteLiteral(">Add</button>\n\n\n");

        }
    }
}
#pragma warning restore 1591
