#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTests.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
	using WebMatrix.WebData;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n  <head>\r\n      <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n      <title>");

            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
        Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n      <link");

WriteAttribute("href", Tuple.Create(" href=\"", 125), Tuple.Create("\"", 145)
, Tuple.Create(Tuple.Create("", 132), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 132), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n      <script");

WriteAttribute("src", Tuple.Create(" src=\"", 204), Tuple.Create("\"", 239)
, Tuple.Create(Tuple.Create("", 210), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-1.9.1.min.js")
, 210), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\n      <script");

WriteAttribute("src", Tuple.Create(" src=\"", 287), Tuple.Create("\"", 319)
, Tuple.Create(Tuple.Create("", 293), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/bootstrap.min.js")
, 293), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\n      <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 382), Tuple.Create("\"", 416)
, Tuple.Create(Tuple.Create("", 389), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.min.css")
, 389), false)
);

WriteLiteral(">\r\n      <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 448), Tuple.Create("\"", 473)
, Tuple.Create(Tuple.Create("", 455), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 455), false)
);

WriteLiteral(">\r\n      <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n      <!-- TODO: The odd thing is, even when we include this, we still have " +
"to explicitly link the bootstrap.min.css file -->\r\n      <!-- [at]Styles.Render(" +
"\"~/Content/css\") --> \r\n");

WriteLiteral("      ");

            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
 Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </head>\r\n  <body>\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(@">DPW Works!</a>

        <!-- The site name is overridden when the site-wide admin is using the system and has selected a site. -->
        <!-- Otherwise, the site name is determined from the site associated with the logged in user -->
        <!-- TODO: Test: site-wide admin logs in, selects a site, logs out, user logs in -- is the ViewBag div restored? -->
        <div");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" id=\"siteName\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
                                           Write(Session["SiteName"]);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n        <div");

WriteLiteral(" class=\"btn-group navbar-right\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"padding-top8 padding-right20\"");

WriteLiteral(">\r\n               <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-topbar\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1518), Tuple.Create("\"", 1572)
, Tuple.Create(Tuple.Create("", 1528), Tuple.Create("location.href=\'", 1528), true)
            
            #line 27 "..\..\Views\Shared\_Layout.cshtml"
                , Tuple.Create(Tuple.Create("", 1543), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 1543), false)
, Tuple.Create(Tuple.Create("", 1571), Tuple.Create("\'", 1571), true)
);

WriteLiteral(">Home</button>\r\n               <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-topbar\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1660), Tuple.Create("\"", 1714)
, Tuple.Create(Tuple.Create("", 1670), Tuple.Create("location.href=\'", 1670), true)
            
            #line 28 "..\..\Views\Shared\_Layout.cshtml"
                , Tuple.Create(Tuple.Create("", 1685), Tuple.Create<System.Object, System.Int32>(Url.Action("About", "Home")
            
            #line default
            #line hidden
, 1685), false)
, Tuple.Create(Tuple.Create("", 1713), Tuple.Create("\'", 1713), true)
);

WriteLiteral(">About</button>\r\n               <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-topbar\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1803), Tuple.Create("\"", 1859)
, Tuple.Create(Tuple.Create("", 1813), Tuple.Create("location.href=\'", 1813), true)
            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
                , Tuple.Create(Tuple.Create("", 1828), Tuple.Create<System.Object, System.Int32>(Url.Action("Contact", "Home")
            
            #line default
            #line hidden
, 1828), false)
, Tuple.Create(Tuple.Create("", 1858), Tuple.Create("\'", 1858), true)
);

WriteLiteral(">Contact</button>\r\n\r\n");

            
            #line 31 "..\..\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\_Layout.cshtml"
                 if (WebSecurity.IsAuthenticated)
                {

            
            #line default
            #line hidden
WriteLiteral("                   <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-topbar\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2026), Tuple.Create("\"", 2081)
, Tuple.Create(Tuple.Create("", 2036), Tuple.Create("location.href=\'", 2036), true)
            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
                    , Tuple.Create(Tuple.Create("", 2051), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout", "Home")
            
            #line default
            #line hidden
, 2051), false)
, Tuple.Create(Tuple.Create("", 2080), Tuple.Create("\'", 2080), true)
);

WriteLiteral(">Logout</button>\r\n");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("             </div>\r\n        </div>\r\n    </nav>\r\n\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-3 col-md-2 sidebar\"");

WriteLiteral(">\r\n\r\n          <!-- site-wide admin page stuff -->\r\n");

            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
             if (WebSecurity.IsAuthenticated)
            {

            
            #line default
            #line hidden
WriteLiteral("              <ul");

WriteLiteral(" class=\"nav nav-sidebar\"");

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
                   if (User.IsInRole("Site-Wide Administrator"))
                  {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteLiteral(" href=\"/Admin/SiteManagement\"");

WriteLiteral(">Sites</a></li>\r\n");

WriteLiteral("                    <li><a");

WriteLiteral(" href=\"/Admin/RoleManagement\"");

WriteLiteral(">Roles</a></li>\r\n");

            
            #line 51 "..\..\Views\Shared\_Layout.cshtml"
                  }

            
            #line default
            #line hidden
WriteLiteral("                  ");

            
            #line 52 "..\..\Views\Shared\_Layout.cshtml"
                   if ( (User.IsInRole("Site-Wide Administrator") || User.IsInRole("Administrator")) && (Session["SiteId"] != null) )
                  {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteLiteral(" href=\"/Admin/UserManagement\"");

WriteLiteral(">Users</a></li>\r\n");

            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
                  }

            
            #line default
            #line hidden
WriteLiteral("              </ul>\r\n");

            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <!-- separate these admin functions -->                \r\n");

            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
                if ( (User.IsInRole("Site-Wide Administrator") || User.IsInRole("Administrator")) && (Session["SiteId"] != null) )
                {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"nav nav-sidebar\"");

WriteLiteral(">\r\n                    <li><a");

WriteLiteral(" href=\"/Admin/UnitManagement\"");

WriteLiteral(">Units</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"/Admin/LaborRateManagement\"");

WriteLiteral(">Labor Rates</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"/Admin/EquipmentManagement\"");

WriteLiteral(">Equipment</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"/Admin/MaterialManagement\"");

WriteLiteral(">Material</a></li>\r\n                </ul>\r\n");

            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"
                }


            
            #line default
            #line hidden
WriteLiteral("              <!-- user stuff -->\r\n");

WriteLiteral("                <!-- we see this only when we have a site selected. -->\r\n");

WriteLiteral("              <ul");

WriteLiteral(" class=\"nav nav-sidebar\"");

WriteLiteral(">\r\n                <li><a");

WriteLiteral(" href=\"/Estimates/NewEstimate\"");

WriteLiteral(">Create Estimate</a></li>\r\n                <li><a");

WriteLiteral(" href=\"/Estimates/ViewEstimates\"");

WriteLiteral(">View Estimates</a></li>\r\n                <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Reports</a></li>\r\n                <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Preferences</a></li>\r\n                <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Account Settings</a></li>\r\n              </ul>\r\n");

            
            #line 78 "..\..\Views\Shared\_Layout.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n          <!-- unregistered and registered users -->\r\n          <ul");

WriteLiteral(" class=\"nav nav-sidebar\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Report A Problem</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Contact Us</a></li>\r\n            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"\"");

WriteLiteral(">Sign In</a></li>\r\n          </ul>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\"");

WriteLiteral(">\r\n");

WriteLiteral("           ");

            
            #line 89 "..\..\Views\Shared\_Layout.cshtml"
      Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
            <!-- Needed for the default account cshtml stuff, where at the end, you find [at]section Scripts {[at]Scripts.Render(""~/bundles/jqueryval"") }  -->
            <!-- Must add the parameter false to indicate that the section is not required. -->
");

WriteLiteral("           ");

            
            #line 92 "..\..\Views\Shared\_Layout.cshtml"
      Write(RenderSection("Scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n      </div>\r\n    </div>\r\n\r\n    <footer>\r\n      <div");

WriteLiteral(" class=\"text-center padding-top8\"");

WriteLiteral(">&copy; ");

            
            #line 98 "..\..\Views\Shared\_Layout.cshtml"
                                              Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - dpworks.org<br />\r\n            Developed by <a");

WriteLiteral(" href=\"http://www.marcclifton.com\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Marc Clifton</a></div>\r\n    </footer>\r\n  </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
