#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTests.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/_BootstrapLogin.cshtml")]
    public partial class BootstrapLogin : System.Web.Mvc.WebViewPage<dynamic>
    {
        public BootstrapLogin()
        {
        }
        public override void Execute()
        {
WriteLiteral("<section");

WriteLiteral(" id=\"login\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    \t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    \t    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n        \t    <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n                <h1>Log in with your email address:</h1>\r\n                    " +
"<form");

WriteLiteral(" action=\"/\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"login-form\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"email\"");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Email</label>\r\n                            <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" name=\"email\"");

WriteLiteral(" id=\"email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Email Address\"");

WriteLiteral(">\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"key\"");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Password</label>\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(" id=\"key\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Password\"");

WriteLiteral(">\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"character-checkbox\"");

WriteLiteral(" onclick=\"rememberMe()\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">Remember me?</span>\r\n                        </div>\r\n                        <in" +
"put");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"btn-login\"");

WriteLiteral(" class=\"btn btn-custom btn-lg btn-block\"");

WriteLiteral(" value=\"Log in\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"RememberMe\"");

WriteLiteral(" name=\"RememberMe\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                    </form>\r\n                    <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"forget\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\".forget-modal\"");

WriteLiteral(">Forgot your password?</a>\r\n                    <hr>\r\n        \t    </div>\r\n    \t\t" +
"</div> <!-- /.col-xs-12 -->\r\n    \t</div> <!-- /.row -->\r\n    </div> <!-- /.conta" +
"iner -->\r\n</section>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
