#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTests.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/About.cshtml")]
    public partial class About : System.Web.Mvc.WebViewPage<dynamic>
    {
        public About()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\About.cshtml"
  
    ViewBag.Title = "About";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Home\About.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>");

            
            #line 7 "..\..\Views\Home\About.cshtml"
   Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n</hgroup>\r\n-->\r\n<article>\r\n    <p>\r\n        TODO: Fill this in...\r\n    </p" +
">\r\n</article>\r\n<!--\r\n<aside>\r\n    <h3>Aside Title</h3>\r\n    <p>\r\n        Use thi" +
"s area to provide additional information.\r\n    </p>\r\n    <ul>\r\n        <li>");

            
            #line 22 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 23 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 24 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("Contact", "Contact", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ul>\r\n</aside>\r\n-->");

        }
    }
}
#pragma warning restore 1591
