#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorTests.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Contact.cshtml")]
    public partial class Contact : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Contact()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Contact.cshtml"
  
    ViewBag.Title = "Contact";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<p>TODO: Contact form:</p>");

        }
    }
}
#pragma warning restore 1591
